LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := libglapi
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libglapi
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := $(TARGET_BOARD_PLATFORM)/lib/x86/libglapi$(LOCAL_MODULE_SUFFIX)
LOCAL_SRC_FILES_64 := $(TARGET_BOARD_PLATFORM)/lib/x86_64/libglapi$(LOCAL_MODULE_SUFFIX)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := i965_dri
LOCAL_MODULE_RELATIVE_PATH := dri
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := i965_dri
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := $(TARGET_BOARD_PLATFORM)/lib/x86/dri/i965_dri$(LOCAL_MODULE_SUFFIX)
LOCAL_SRC_FILES_64 := $(TARGET_BOARD_PLATFORM)/lib/x86_64/dri/i965_dri$(LOCAL_MODULE_SUFFIX)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libGLES_mesa
LOCAL_MODULE_RELATIVE_PATH := egl
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := libGLES_mesa
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_SHARED_LIBRARIES := libglapi
LOCAL_REQUIRED_MODULES := i965_dri
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := $(TARGET_BOARD_PLATFORM)/lib/x86/egl/libGLES_mesa$(LOCAL_MODULE_SUFFIX)
LOCAL_SRC_FILES_64 := $(TARGET_BOARD_PLATFORM)/lib/x86_64/egl/libGLES_mesa$(LOCAL_MODULE_SUFFIX)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := vulkan.$(TARGET_BOARD_PLATFORM)
LOCAL_MODULE_RELATIVE_PATH := hw
LOCAL_PROPRIETARY_MODULE := true
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_STEM := vulkan.$(TARGET_BOARD_PLATFORM)
LOCAL_MODULE_SUFFIX := $(TARGET_SHLIB_SUFFIX)
LOCAL_MODULE_OWNER := intel
LOCAL_MULTILIB := both
LOCAL_SRC_FILES_32 := $(TARGET_BOARD_PLATFORM)/lib/x86/hw/vulkan.$(TARGET_BOARD_PLATFORM)$(LOCAL_MODULE_SUFFIX)
LOCAL_SRC_FILES_64 := $(TARGET_BOARD_PLATFORM)/lib/x86_64/hw/vulkan.$(TARGET_BOARD_PLATFORM)$(LOCAL_MODULE_SUFFIX)
include $(BUILD_PREBUILT)
